<?php

namespace AppBundle\Entity;

/**
 * MiniUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiniUserRepository extends \Doctrine\ORM\EntityRepository
{
}
