<?php

namespace AppBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCategoryProducts($categoryId)
  {
    $productsQuery = $this->getEntityManager()
        ->createQuery(
        'SELECT p, c FROM AppBundle:Product p 
         JOIN p.category c ORDER BY p.category ASC, p.id'
    );
    return $productsQuery->getResult();
  }
}
